version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: commentsystem_backend
    volumes:
      - ./backend:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://user:password@db:5432/commentsystem

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: commentsystem_frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8001/api

  db:
    image: postgres:13
    container_name: commentsystem_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=commentsystem
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data:

